# https://circleci.com/docs/2.0/workflows/

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9-stretch-browsers
      - image: circleci/python:3.7-rc-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            - dependencies-cache
      - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
      - store_artifacts:
          path: dist

  test:
    docker:
      - image: circleci/node:8.9-stretch-browsers
      - image: circleci/python:3.7-rc-stretch-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run: yarn coverage

  deploy:
    docker:
      - image: circleci/node:8.9-stretch-browsers
      - image: circleci/python:3.7-rc-stretch-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn install
      - run: yarn deploy

  tag:
    docker:
      - image: circleci/node:8.9-stretch-browsers
    steps:
      - checkout
      - run: git tag "v0.1.$CIRCLE_BUILD_NUM-$CIRCLE_BRANCH"
      - run: git tag
      - run: git push origin "v0.1.$CIRCLE_BUILD_NUM-$CIRCLE_BRANCH"
      
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
      - tag:
          requires:
            - deploy
