service: my-website

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2

plugins:
  - serverless-finch

custom:
  client:
    bucketName: dev.johngeddes.tech
    distributionFolder: dist
    indexDocument: index.html
    errorDocument: index.html
